# A staring point is the basic NIXOS configuration generated by the ISO installer.
# On an existing NIXOS install you can use the following command in your flakes basedir:
# sudo nixos-generate-config --dir ./hosts/m3tam3re
#
# Please make sure to change the first couple of lines in your configuration.nix:
{ config, inputs, ouputs, lib, pkgs, ... }:

{
  imports = [ 
  # ./hardware-configuration.nix
    inputs.home-manager.nixosModules.home-manager
  ];

# Moreover please update the packages option in your user configuration and add the home-manager options:
users.users = {
  xhuyz = {
    isNormalUser = true;
    initialPassword = "xhuyz";
    extraGroups = [ "wheel" ]; 
    packages = [ inputs.home-manager.packages.${pkgs.system}.default ];
  };
};

home-manager = {
  useUserPackages = true;
  extraSpecialArgs = { inherit inputs outputs; };
  users.m3tam3re =
    import ../../home/xhuyz/${config.networking.hostname}.nix;
};

# Please also change your hostname accordingly:
#:w
networking.hostName = "develop"; # Define your hostname.
{
  imports = [
    ../common
    ./configuration.nix
    ./programs.nix
    # ./secrets.nix
    ./services
  ];

  # extraServices = {
  #   flatpak.enable = false;
  #   ollama.enable = false;
  #   podman.enable = true;
  #   virtualisation.enable = false;
  # };
}
